
project_id = "ojueihcytxwcioqtvwez"

[functions.create-xtream-account]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.test-megaott]
verify_jwt = false

[functions.megaott-subscription]
verify_jwt = true
