
project_id = "ojueihcytxwcioqtvwez"

[functions.create-xtream-account]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

# Removed Stripe webhook function
verify_jwt = false
